export const CANONICAL_DESIGN_TOKEN_KEYS = [
  'primary',
  'primary-container',
  'primary-fixed',
  'on-primary',
  'on-primary-container',
  'on-primary-fixed',
  'secondary',
  'tertiary',
  'secondary-container',
  'on-secondary',
  'on-secondary-container',
  'surface',
  'surface-container-low',
  'surface-container-lowest',
  'surface-container-high',
  'surface-bright',
  'surface-tint',
  'surface-variant',
  'on-surface',
  'on-surface-variant',
  'outline',
  'outline-variant',
  'success',
  'success-container',
  'on-success',
  'on-success-container',
  'warning',
  'warning-container',
  'on-warning',
  'on-warning-container',
  'error',
  'error-container',
  'on-error',
  'on-error-container',
  'info',
  'info-container',
  'on-info',
  'on-info-container',
  'primary-hover',
  'primary-pressed',
  'primary-focus',
  'primary-disabled',
  'secondary-hover',
  'secondary-pressed',
  'secondary-focus',
  'secondary-disabled',
  'trend-positive',
  'trend-positive-container',
  'on-trend-positive-container',
  'trend-negative',
  'trend-negative-container',
  'on-trend-negative-container',
  'trend-neutral',
  'trend-neutral-container',
  'on-trend-neutral-container',
  'category-technical',
  'category-technical-container',
  'on-category-technical-container',
  'category-randori',
  'category-randori-container',
  'on-category-randori-container',
  'category-shiai',
  'category-shiai-container',
  'on-category-shiai-container',
] as const;

export type CanonicalDesignTokenKey =
  (typeof CANONICAL_DESIGN_TOKEN_KEYS)[number];

const kebabCaseTokenPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const isKebabCaseDesignTokenKey = (value: string): boolean =>
  kebabCaseTokenPattern.test(value);
